services:
  telegram-mega-rename-bot:
    build:
      type: dockerfile
      dockerfile: ./deploy/Dockerfile.prod
    deployment:
      port: 8000
    env:
      - name: TELEGRAM_BOT_TOKEN
        value: "your_telegram_bot_token_here"
